name: CI
on:
  pull_request:

jobs:
  CI:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.0
        with:
          node-version: 14
      - name: Install SDK
        run: |
          npm install
      - name: Run Linter
        run: |
          npm run lint