name: CodeCov
on:
  push:
    branches: 
      - main
  pull_request:
  schedule:
    - cron: 0 0 * * *

jobs:
  Unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'
      - name: Install SDK
        run: |
          npm install
      - name: Generate Unit Test Coverage
        run: |
          npm run coverage:unit
      - name: Publish Coverage
        uses: codecov/codecov-action@v1.2.0
        with:
          flags: unit
          fail_ci_if_error: true