name: Spec Update
on: 
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: 0 0 * * *

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v2.1.2
        with:
          python-version: 2.7
      - name: Setup Node.JS environment
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 14
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY_MM_DD
          utcOffset: "-08:00"
      - name: Install SDK
        run: |
          npm install
      - name: Update Modules
        run: |
          git submodule init
          git submodule update --remote --recursive
      - name: Generate Branch Name
        id: git-branch
        run: |
          echo "::set-output name=branch::spec_update_${{ steps.current-time.outputs.formattedTime }}"
      - name: Generate Num Diffs
        id: git-diff-num
        run: |
          cd codegen/
          diffs=$(git diff --submodule spec | grep ">" | wc -l)
          echo "$diffs"
          echo "::set-output name=num-diff::$diffs"
          cd ..
      - name: Generate Diff
        id: git-diff
        run: |
          cd codegen/spec
          gitdiff=$(git log -n ${{ steps.git-diff-num.outputs.num-diff }} --pretty="format:%n %H %n%n %b")
          diffCommit="Automated Spec Update \n $gitdiff"
          diffCommit="${diffCommit//'%'/'%25'}"
          diffCommit="${diffCommit//$'\n'/'%0A'}"
          diffCommit="${diffCommit//$'\r'/'%0D'}"
          echo "$diffCommit"
          echo "::set-output name=diff::$gitdiff"
          echo "::set-output name=commitDiff::$diffCommit"
          cd ../..
      - name: Generate New Routes
        run: |
          echo "${{ steps.git-diff.outputs.commitDiff}}"
          cd codegen/stone
          python setup.py install
          cd ..
          sh ./run_codegen.sh
          cd ..
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.3.0
        if: steps.git-diff-num.outputs.num-diff != 0
        with:
          token: ${{ secrets.SPEC_UPDATE_TOKEN }}
          commit-message: |
            ${{ steps.git-diff.outputs.commitDiff}}
          branch: ${{ steps.git-branch.outputs.branch }}
          delete-branch: true
          title: 'Automated Spec Update'
          base: 'master'
          team-reviewers: |
            owners
            maintainers
          draft: false